app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /api
    defaults:
        _format: json


#api:
#    resource: '@AppBundle/Controller/Api'
#    type: annotation
#    prefix: /api
#    defaults:
#        _format: json

